# Generated by Django 6.0.1 on 2026-08-13 08:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('barangay_id', models.AutoField(primary_key=True, serialize=False)),
                ('barangay_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('humidity', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('CHO', 'City Health Office'), ('CHW', 'City Health Worker'), ('BHW', 'Barangay Health Worker'), ('LGU', 'Local Government Unit')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DengueCase',
            fields=[
                ('dengue_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_age', models.IntegerField()),
                ('patient_sex', models.CharField(max_length=20)),
                ('date_reported', models.DateField()),
                ('case_status', models.CharField(default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('case_count', models.IntegerField(default=1)),
                ('patient_blood_type', models.CharField(blank=True, max_length=5)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dengue_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntegratedDengueDataset',
            fields=[
                ('integrated_dengue_dataset_id', models.AutoField(primary_key=True, serialize=False)),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('dengue_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrated_datasets', to='monitoring.denguecase')),
            ],
        ),
        migrations.CreateModel(
            name='HotspotPrediction',
            fields=[
                ('hotspot_prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('prediction_date', models.DateField()),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('hotspot_level', models.CharField(blank=True, max_length=50)),
                ('forecast_result', models.TextField(blank=True)),
                ('analysis_remarks', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, max_length=50)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_predictions', to='monitoring.barangay')),
                ('integrated_dengue_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='monitoring.integrateddenguedataset')),
            ],
        ),
        migrations.CreateModel(
            name='Purok',
            fields=[
                ('purok_id', models.AutoField(primary_key=True, serialize=False)),
                ('purok_name', models.CharField(max_length=100)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puroks', to='monitoring.barangay')),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='purok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='monitoring.purok'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=100)),
                ('recommendation', models.TextField(blank=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('hotspot_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='monitoring.hotspotprediction')),
            ],
        ),
    ]
