# Generated by Django 6.0.1 on 2026-08-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='purok',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('CHO', 'City Health Office (CHO)'), ('CHW', 'City Health Worker (CHW)'), ('BHW', 'Barangay Health Worker (BHW)'), ('LGU', 'Local Government Unit (LGU)')], default='BHW', max_length=10),
        ),
    ]
