# Generated by Django 6.0.1 on 2026-09-07 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_useraccount_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='assigned_barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bhws', to='monitoring.barangay'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='assigned_purok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bhws', to='monitoring.purok'),
        ),
    ]
