# Generated by Django 6.0.1 on 2026-09-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_useraccount_assigned_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denguecase',
            name='barangay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dengue_cases', to='monitoring.barangay'),
        ),
        migrations.AddField(
            model_name='denguecase',
            name='purok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dengue_cases', to='monitoring.purok'),
        ),
        migrations.AlterField(
            model_name='denguecase',
            name='case_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Active', 'Active'), ('Recovered', 'Recovered'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
