# Generated by Django 6.0.1 on 2026-09-21 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_integrateddenguedataset_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_community_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityreport',
            name='staff_response',
            field=models.TextField(blank=True),
        ),
    ]
